# Generated by Django 5.2 on 2025-05-10 18:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamodel',
            name='dias_semana',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default=[], max_length=100),
        ),
    ]
