# Generated by Django 5.2 on 2025-05-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotina', '0003_conclusoesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reset', models.DateField()),
            ],
        ),
    ]
